# .github/workflows/docker-build-only.yml

name: Build Docker Image Only

on:
  push:
    branches:
      - main
    # You can add other triggers as needed
    # For example, on pull requests:
    # pull_request:
    #   branches:
    #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Disable pushing to any registry
          tags: image-search-api:latest  # Local tag